# ============================================
# Frontend Environment Setup Script
# Sets NEXT_PUBLIC_API_URL and fixes lockfile warnings
# ============================================

param(
    [string]$ApiUrl = "http://localhost:8000"
)

Write-Host "🔧 Setting up Frontend Environment..." -ForegroundColor Cyan

# Get the frontend directory (script location)
$FrontendDir = $PSScriptRoot
if (-not $FrontendDir) {
    $FrontendDir = Get-Location
}

Write-Host "Frontend directory: $FrontendDir" -ForegroundColor Gray

# Step 1: Create or update .env.local file
$EnvFile = Join-Path $FrontendDir ".env.local"
$EnvContent = @"
# Auto-generated by setup-env.ps1
NEXT_PUBLIC_API_URL=$ApiUrl
"@

if (Test-Path $EnvFile) {
    Write-Host "📝 Updating existing .env.local..." -ForegroundColor Yellow
    # Read existing content
    $ExistingContent = Get-Content $EnvFile -Raw
    
    # Update or add NEXT_PUBLIC_API_URL
    if ($ExistingContent -match "NEXT_PUBLIC_API_URL=") {
        $UpdatedContent = $ExistingContent -replace "NEXT_PUBLIC_API_URL=.*", "NEXT_PUBLIC_API_URL=$ApiUrl"
        Set-Content -Path $EnvFile -Value $UpdatedContent -NoNewline
        Write-Host "✅ Updated NEXT_PUBLIC_API_URL to $ApiUrl" -ForegroundColor Green
    } else {
        Add-Content -Path $EnvFile -Value "`nNEXT_PUBLIC_API_URL=$ApiUrl"
        Write-Host "✅ Added NEXT_PUBLIC_API_URL=$ApiUrl" -ForegroundColor Green
    }
} else {
    Write-Host "📝 Creating new .env.local..." -ForegroundColor Yellow
    Set-Content -Path $EnvFile -Value $EnvContent
    Write-Host "✅ Created .env.local with NEXT_PUBLIC_API_URL=$ApiUrl" -ForegroundColor Green
}

# Step 2: Fix multiple lockfiles warning
Write-Host "`n🔍 Checking for lockfile issues..." -ForegroundColor Cyan

$PackageLockJson = Join-Path $FrontendDir "package-lock.json"
$YarnLock = Join-Path $FrontendDir "yarn.lock"
$PnpmLock = Join-Path $FrontendDir "pnpm-lock.yaml"

$LockFilesFound = @()
if (Test-Path $PackageLockJson) { $LockFilesFound += "package-lock.json" }
if (Test-Path $YarnLock) { $LockFilesFound += "yarn.lock" }
if (Test-Path $PnpmLock) { $LockFilesFound += "pnpm-lock.yaml" }

if ($LockFilesFound.Count -gt 1) {
    Write-Host "⚠️  Multiple lockfiles detected: $($LockFilesFound -join ', ')" -ForegroundColor Yellow
    Write-Host "📦 Keeping package-lock.json (npm), removing others..." -ForegroundColor Yellow
    
    # Keep package-lock.json, remove others
    if (Test-Path $YarnLock) {
        Remove-Item $YarnLock -Force
        Write-Host "✅ Removed yarn.lock" -ForegroundColor Green
    }
    if (Test-Path $PnpmLock) {
        Remove-Item $PnpmLock -Force
        Write-Host "✅ Removed pnpm-lock.yaml" -ForegroundColor Green
    }
    
    Write-Host "✅ Lockfile cleanup complete. Using npm (package-lock.json)" -ForegroundColor Green
} else {
    Write-Host "✅ No lockfile conflicts detected" -ForegroundColor Green
}

# Step 3: Verify .gitignore includes .env.local
$GitIgnore = Join-Path $FrontendDir ".gitignore"
if (Test-Path $GitIgnore) {
    $GitIgnoreContent = Get-Content $GitIgnore -Raw
    if ($GitIgnoreContent -notmatch "\.env\.local") {
        Write-Host "📝 Adding .env.local to .gitignore..." -ForegroundColor Yellow
        Add-Content -Path $GitIgnore -Value "`n# Environment variables`n.env.local`n"
        Write-Host "✅ Added .env.local to .gitignore" -ForegroundColor Green
    }
} else {
    Write-Host "📝 Creating .gitignore..." -ForegroundColor Yellow
    Set-Content -Path $GitIgnore -Value "# Environment variables`n.env.local`n"
    Write-Host "✅ Created .gitignore with .env.local" -ForegroundColor Green
}

Write-Host "`n✨ Setup complete!" -ForegroundColor Green
Write-Host "   API URL: $ApiUrl" -ForegroundColor Gray
Write-Host "   Environment file: $EnvFile" -ForegroundColor Gray
Write-Host "`n💡 To use a different API URL, run:" -ForegroundColor Cyan
Write-Host "   .\setup-env.ps1 -ApiUrl 'http://your-backend-url:port'" -ForegroundColor White









