# ============================================================
# ONEPACK v11 — FunAging.club FULL STACK AUTO MODE
# Backend + Frontend + Healthcheck + Auto Start
# ============================================================

param(
    [switch]$SkipFrontend
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "  ONEPACK v11 — FunAging.club FULL STACK AUTO MODE" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""

$root = Get-Location
$backend = Join-Path $root "backend"
$frontend = Join-Path $root "frontend"

# -------------------------------------------------------------------
# 1) FIX Dockerfile.backend (Safe overwrite)
# -------------------------------------------------------------------
Write-Host "[1] Fixing Dockerfile.backend..." -ForegroundColor Yellow

$dockerfile = Join-Path $backend "Dockerfile.backend"
if (Test-Path $dockerfile) {
    $content = Get-Content $dockerfile -Raw
    
    # Replace incorrect COPY paths
    $content = $content -replace "COPY backend/requirements.txt", "COPY requirements.txt"
    $content = $content -replace "COPY backend/app", "COPY app"
    
    Set-Content -Path $dockerfile -Value $content -NoNewline
    Write-Host "  ✔ Dockerfile.backend fixed" -ForegroundColor Green
} else {
    Write-Warning "  Dockerfile.backend not found. Skipping fix."
}

# -------------------------------------------------------------------
# 2) Ensure frontend/.env.local exists with minimal required vars
# -------------------------------------------------------------------
Write-Host "`n[2] Ensuring frontend/.env.local exists..." -ForegroundColor Yellow

if (-not (Test-Path $frontend)) {
    New-Item -ItemType Directory -Path $frontend | Out-Null
    Write-Host "  Created frontend/ directory" -ForegroundColor Green
}

$envLocal = Join-Path $frontend ".env.local"
$envContent = @"
# Auto-generated by ONEPACK v11
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
NEXT_PUBLIC_API_URL=http://localhost:8000
"@

if (Test-Path $envLocal) {
    Write-Host "  frontend/.env.local already exists" -ForegroundColor Yellow
    Write-Host "  → Please verify NEXT_PUBLIC_API_URL is set correctly" -ForegroundColor Cyan
} else {
    Set-Content -Path $envLocal -Value $envContent
    Write-Host "  ✔ Created frontend/.env.local with minimal config" -ForegroundColor Green
}

# -------------------------------------------------------------------
# 3) Stop existing containers
# -------------------------------------------------------------------
Write-Host "`n[3] Stopping existing containers..." -ForegroundColor Yellow

try {
    docker compose -f docker-compose.sas.yml down 2>&1 | Out-Null
    Write-Host "  ✔ Stopped existing containers" -ForegroundColor Green
} catch {
    Write-Host "  No existing containers to stop" -ForegroundColor Gray
}

# -------------------------------------------------------------------
# 4) Build backend
# -------------------------------------------------------------------
Write-Host "`n[4] Building backend Docker image..." -ForegroundColor Yellow

try {
    docker compose -f docker-compose.sas.yml build sas_backend
    Write-Host "  ✔ Backend image built successfully" -ForegroundColor Green
} catch {
    Write-Warning "  Backend build failed: $($_.Exception.Message)"
    exit 1
}

# -------------------------------------------------------------------
# 5) Start stack (backend + db)
# -------------------------------------------------------------------
Write-Host "`n[5] Starting Docker stack (sas_db + sas_backend)..." -ForegroundColor Yellow

try {
    docker compose -f docker-compose.sas.yml up -d
    Write-Host "  ✔ Docker stack started" -ForegroundColor Green
} catch {
    Write-Warning "  Failed to start Docker stack: $($_.Exception.Message)"
    exit 1
}

# -------------------------------------------------------------------
# 6) Wait for backend
# -------------------------------------------------------------------
Write-Host "`n[6] Waiting for backend to be ready..." -ForegroundColor Yellow
Start-Sleep -Seconds 8
Write-Host "  ✔ Wait complete" -ForegroundColor Green

# -------------------------------------------------------------------
# 7) Healthcheck backend
# -------------------------------------------------------------------
Write-Host "`n[7] Backend health check..." -ForegroundColor Yellow
Write-Host "=== BACKEND HEALTHCHECK ===" -ForegroundColor Cyan

$backendHealthy = $false
$healthUrls = @("http://localhost:8000/health", "http://localhost:8000/")

foreach ($url in $healthUrls) {
    try {
        $response = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5
        if ($response.StatusCode -eq 200) {
            Write-Host "  ✔ Backend healthy: $url" -ForegroundColor Green
            Write-Host "    Response: $($response.Content)" -ForegroundColor Gray
            $backendHealthy = $true
            break
        }
    } catch {
        Write-Warning "    Failed: $url - $($_.Exception.Message)"
    }
}

if (-not $backendHealthy) {
    Write-Warning "  Backend health check failed. Check logs with: docker logs sas_backend"
}

# -------------------------------------------------------------------
# 8) Frontend: install deps + run dev
# -------------------------------------------------------------------
if (-not $SkipFrontend) {
    Write-Host "`n[8] Setting up frontend..." -ForegroundColor Yellow
    
    if (-not (Test-Path $frontend)) {
        Write-Warning "  frontend/ directory not found. Skipping frontend setup."
    } else {
        Push-Location $frontend
        
        # Check if node_modules exists
        $nodeModules = Join-Path $frontend "node_modules"
        if (-not (Test-Path $nodeModules)) {
            Write-Host "  Installing frontend dependencies..." -ForegroundColor Yellow
            try {
                npm install
                Write-Host "  ✔ Frontend dependencies installed" -ForegroundColor Green
            } catch {
                Write-Warning "  npm install failed: $($_.Exception.Message)"
            }
        } else {
            Write-Host "  node_modules already exists. Skipping npm install." -ForegroundColor Gray
        }
        
        # Check if dev server is already running
        try {
            $frontendCheck = Invoke-WebRequest -Uri "http://localhost:3000" -UseBasicParsing -TimeoutSec 2 -ErrorAction SilentlyContinue
            Write-Host "  Frontend dev server already running on port 3000" -ForegroundColor Yellow
        } catch {
            Write-Host "  Starting frontend dev server..." -ForegroundColor Yellow
            Write-Host "  → Run 'npm run dev' manually in frontend/ directory" -ForegroundColor Cyan
            Write-Host "  → Or use: cd frontend && npm run dev" -ForegroundColor Cyan
        }
        
        Pop-Location
    }
} else {
    Write-Host "`n[8] Skipping frontend (SkipFrontend flag set)" -ForegroundColor Yellow
}

# -------------------------------------------------------------------
# 9) Check frontend localhost:3000
# -------------------------------------------------------------------
if (-not $SkipFrontend) {
    Write-Host "`n[9] Frontend health check..." -ForegroundColor Yellow
    Write-Host "=== FRONTEND HEALTHCHECK ===" -ForegroundColor Cyan
    
    Start-Sleep -Seconds 2
    
    try {
        $frontendResponse = Invoke-WebRequest -Uri "http://localhost:3000" -UseBasicParsing -TimeoutSec 5
        if ($frontendResponse.StatusCode -eq 200) {
            Write-Host "  ✔ Frontend available: http://localhost:3000" -ForegroundColor Green
        }
    } catch {
        Write-Host "  ⚠ Frontend not yet available on http://localhost:3000" -ForegroundColor Yellow
        Write-Host "    → Start manually: cd frontend && npm run dev" -ForegroundColor Cyan
    }
}

# -------------------------------------------------------------------
# DONE
# -------------------------------------------------------------------
Write-Host ""
Write-Host "=======================================================" -ForegroundColor Cyan
Write-Host "  ONEPACK v11 COMPLETE — FULL STACK ONLINE" -ForegroundColor Green
Write-Host "=======================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Backend:  http://localhost:8000/health" -ForegroundColor White
if (-not $SkipFrontend) {
    Write-Host "Frontend: http://localhost:3000" -ForegroundColor White
    Write-Host ""
    Write-Host "To start frontend manually:" -ForegroundColor Cyan
    Write-Host "  cd frontend" -ForegroundColor White
    Write-Host "  npm run dev" -ForegroundColor White
}
Write-Host ""
Write-Host "To view logs:" -ForegroundColor Cyan
Write-Host "  docker logs sas_backend" -ForegroundColor White
Write-Host "  docker logs sas_db" -ForegroundColor White
Write-Host ""
