// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Helper function to clean and extract env value
const getEnvValue = (value: string | undefined): string => {
  if (!value) return '';
  // Remove quotes if present (both single and double)
  return String(value).replace(/^["']|["']$/g, '').trim();
};

// Get Supabase URL - support multiple ways of configuration
const SUPABASE_URL_RAW = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PROJECT_ID_RAW = import.meta.env.VITE_SUPABASE_PROJECT_ID || '';
const SUPABASE_URL = 
  getEnvValue(SUPABASE_URL_RAW) || 
  (getEnvValue(SUPABASE_PROJECT_ID_RAW) 
    ? `https://${getEnvValue(SUPABASE_PROJECT_ID_RAW)}.supabase.co` 
    : '');

// Get Supabase key - support multiple variable names
const SUPABASE_PUBLISHABLE_KEY = 
  getEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) || 
  getEnvValue(import.meta.env.VITE_SUPABASE_ANON_KEY) || 
  '';

// Check if environment variables are set (must be non-empty after cleaning)
const isConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL !== '' && SUPABASE_PUBLISHABLE_KEY !== '');

if (!isConfigured) {
  console.error('❌ Supabase configuration missing!');
  console.error('Current values:');
  console.error('  VITE_SUPABASE_URL:', SUPABASE_URL_RAW || '[NOT SET]');
  console.error('  VITE_SUPABASE_PROJECT_ID:', SUPABASE_PROJECT_ID_RAW || '[NOT SET]');
  console.error('  VITE_SUPABASE_PUBLISHABLE_KEY:', import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ? '[SET]' : '[NOT SET]');
  console.error('  VITE_SUPABASE_ANON_KEY:', import.meta.env.VITE_SUPABASE_ANON_KEY ? '[SET]' : '[NOT SET]');
  console.error('  Final SUPABASE_URL:', SUPABASE_URL || '[EMPTY]');
  console.error('  Final SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '[SET]' : '[EMPTY]');
  console.error('');
  console.error('Please set the following environment variables:');
  console.error('  Option 1: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error('  Option 2: VITE_SUPABASE_PROJECT_ID and VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error('');
  console.error('Create a .env file in the root directory with:');
  console.error('  VITE_SUPABASE_URL=your_supabase_url');
  console.error('  VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_key');
}

// Create a dummy client if env vars are missing to prevent crashes
const createSupabaseClient = () => {
  if (!isConfigured) {
    // Return a mock client that will fail gracefully
    return createClient<Database>(
      'https://placeholder.supabase.co',
      'placeholder-key',
      {
        auth: {
          storage: localStorage,
          persistSession: false,
          autoRefreshToken: false,
        }
      }
    );
  }
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createSupabaseClient();

// Export a function to check if Supabase is properly configured
export const isSupabaseConfigured = () => {
  return isConfigured;
};