"""
Mock Video Provider
For testing and development without actual AI API calls
"""

from typing import List, Dict, Any, Optional
from app.providers.video_provider_base import (
    VideoProviderBase,
    VideoResult,
    SubtitleResult
)


class MockVideoProvider(VideoProviderBase):
    """Mock video provider for testing"""
    
    def __init__(self, api_key: Optional[str] = None):
        super().__init__(api_key)
        self.name = "mock"
    
    def generate_video(
        self,
        prompt: str,
        duration_seconds: int = 15,
        aspect_ratio: str = "16:9",
        resolution: Optional[str] = None,
        style: Optional[str] = None,
        **kwargs
    ) -> VideoResult:
        """Generate mock video"""
        # Calculate resolution from aspect ratio
        resolutions = {
            "16:9": (1920, 1080),
            "9:16": (1080, 1920),
            "4:5": (1080, 1350),
            "1:1": (1080, 1080)
        }
        width, height = resolutions.get(aspect_ratio, (1920, 1080))
        
        # Create placeholder video URL
        video_url = f"https://via.placeholder.com/{width}x{height}.mp4?text={prompt[:30]}"
        
        return VideoResult(
            video_url=video_url,
            duration=duration_seconds,
            width=width,
            height=height,
            fps=30,
            format="mp4",
            metadata={
                "prompt": prompt,
                "style": style,
                "provider": "mock",
                "generated": True
            }
        )
    
    def edit_video(
        self,
        source_path: str,
        operations: List[Dict[str, Any]],
        output_config: Optional[Dict[str, Any]] = None,
        **kwargs
    ) -> VideoResult:
        """Edit mock video"""
        # Parse operations
        aspect_ratio = "16:9"
        for op in operations:
            if op.get("type") == "auto_reframe":
                aspect_ratio = op.get("target_aspect_ratio", "16:9")
        
        resolutions = {
            "16:9": (1920, 1080),
            "9:16": (1080, 1920),
            "4:5": (1080, 1350),
            "1:1": (1080, 1080)
        }
        width, height = resolutions.get(aspect_ratio, (1920, 1080))
        
        video_url = f"https://via.placeholder.com/{width}x{height}.mp4?text=Edited+Video"
        
        return VideoResult(
            video_url=video_url,
            duration=15.0,  # Mock duration
            width=width,
            height=height,
            fps=30,
            format="mp4",
            metadata={
                "source_path": source_path,
                "operations": operations,
                "provider": "mock",
                "edited": True
            }
        )
    
    def subtitle_video(
        self,
        source_path: str,
        source_language: str = "auto",
        target_languages: Optional[List[str]] = None,
        style: str = "default",
        **kwargs
    ) -> SubtitleResult:
        """Generate mock subtitles"""
        # Mock transcript
        transcript = "This is a mock transcript of the video content. In a real implementation, this would be generated by speech-to-text service."
        
        # Mock segments
        segments = [
            {"start": 0.0, "end": 5.0, "text": "This is a mock transcript"},
            {"start": 5.0, "end": 10.0, "text": "of the video content."},
            {"start": 10.0, "end": 15.0, "text": "In a real implementation..."}
        ]
        
        subtitle_file_url = f"https://via.placeholder.com/subtitle.srt?text=mock"
        
        return SubtitleResult(
            transcript=transcript,
            subtitle_file_url=subtitle_file_url,
            subtitle_format="srt",
            segments=segments,
            metadata={
                "source_path": source_path,
                "source_language": source_language,
                "target_languages": target_languages or [],
                "style": style,
                "provider": "mock",
                "generated": True
            }
        )
    
    def get_cost_estimate(self, operation: str, duration_seconds: Optional[int] = None, **kwargs) -> float:
        """Mock cost estimates - very cheap for testing"""
        return 0.01

